"""Generate plugin/rig_table.h from the chassis skeleton.

    python tools/gen_rig_table.py

Every third-person chassis shares ONE hand rig: checked over all 27 PCVR chassis
skeletons, the finger joint indices, parents and bind rotations are identical.
So the plugin can pose fingers from the rig's own bind pose instead of from a
pose captured in-game -- which depended on what the player's real controllers
were doing at that moment.

Per joint this emits the bind LOCAL rotation (relative to the joint's real
parent -- ring and pinky hang off metacarpal bones, not the hand), the hinge
axis in the joint's local frame, and the local bone direction. Each hinge sign
is chosen by a direct test: rotating that joint alone by +30 degrees must bring
the fingertip closer to the palm pad bone.
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path

import numpy as np

REPO = Path(r"J:\EchoVR-Tools-Launcher\lone_echo_blender")
sys.path.insert(0, str(REPO / "scripts"))
import evr_apply_skeleton as S  # noqa: E402

ROOT = Path(r"H:\pcvr-extracted")
MODEL = "dac6537a23236325"             # cst_body_s11_a; identical hand rig on all chassis
OUT = Path(__file__).resolve().parent.parent / "plugin" / "rig_table.h"
FINGERS = ["Thumb", "Index", "Middle", "Ring", "Pinky"]   # HtvFinger order


def qmul(a, b):
    ax, ay, az, aw = a; bx, by, bz, bw = b
    return np.array([aw*bx + ax*bw + ay*bz - az*by, aw*by - ax*bz + ay*bw + az*bx,
                     aw*bz + ax*by - ay*bx + az*bw, aw*bw - ax*bx - ay*by - az*bz])
def conj(q): return np.array([-q[0], -q[1], -q[2], q[3]])
def qrot(q, v): return qmul(qmul(q, np.array([*v, 0.0])), conj(q))[:3]
def aa(v, deg):
    h = np.radians(deg) / 2
    return np.array([*(np.asarray(v, float) * np.sin(h)), np.cos(h)])
def unit(v): return v / np.linalg.norm(v)


def main():
    blob = (ROOT / "46adff5980245670" / MODEL).read_bytes()
    bind = S.read_bind_pose(ROOT, MODEL)
    n = len(bind)
    par, _, _ = S.find_hierarchy(blob, n)
    names = S.bone_name_table()
    off = S._hierarchy_offset(blob, n)
    def nmf(h): return names.get("%016x" % h) or names.get(h) or names.get(str(h)) or "%016x" % h
    nm = [nmf(struct.unpack_from("<Q", blob, off + 24 * i + 4)[0]) for i in range(n)]
    idx = {v: i for i, v in enumerate(nm)}
    localq = [np.array(b[0], float) / np.linalg.norm(b[0]) for b in bind]
    localt = [np.array(b[1], float) for b in bind]

    # world (standard convention, world = parent * local), rotation + position
    WQ, WP = [None] * n, [None] * n
    def solve(i):
        if WQ[i] is not None: return
        p = par[i]
        if p == S.NO_BONE:
            WQ[i], WP[i] = localq[i], localt[i]
            return
        solve(p)
        WQ[i] = qmul(WQ[p], localq[i])
        WP[i] = WP[p] + qrot(WQ[p], localt[i])
    for i in range(n): solve(i)

    # sanity: our composition must match the repo's validated matrix composition
    Wm = S.world_transforms(bind, par)
    err = max(np.linalg.norm(np.array(Wm[i])[:3, 3] - WP[i]) for i in range(n))
    assert err < 1e-4, "composition mismatch %g" % err

    def chain_tip(side, f, override):
        """World fingertip of finger f after applying extra local rotations."""
        js = [idx["EXP_%s_%s%d" % (side, f, k)] for k in (1, 2, 3)]
        p0 = par[js[0]]
        q, pos = WQ[p0], WP[p0]
        for k, j in enumerate(js):
            pos = pos + qrot(q, localt[j])
            q = qmul(q, localq[j])
            if k in override: q = qmul(q, override[k])
        tipdir = localt[js[2]] / np.linalg.norm(localt[js[2]])   # continue along the last bone
        return pos + qrot(q, tipdir * 0.02)

    lines = ["// Generated by tools/gen_rig_table.py from the chassis skeleton -- do not edit.",
             "// One hand rig is shared by every third-person chassis (checked on all 27).",
             "#pragma once", "#include <stdint.h>", "",
             "struct RigJoint { uint16_t joint; float bindQ[4]; float axis[3]; float bone[3]; float twistSign; };",
             "struct RigFinger { uint16_t parent; RigJoint j[3]; float spreadAxis[3]; };",
             "struct RigHand { uint16_t wrist; RigFinger f[5]; };   // f[] in HtvFinger order", "",
             "static const RigHand g_Rig[2] = {"]
    report = []
    for side in ("L1", "R1"):
        wrist = idx["EXP_%s_Hand1" % side]
        pad = WP[idx["EXP_%s_PalmPad1" % side]]
        kI, kP = WP[idx["EXP_%s_Index1" % side]], WP[idx["EXP_%s_Pinky1" % side]]
        P = unit(kP - kI)                                   # toward the pinky side
        lines.append("  { %d, {   // %s" % (wrist, side))
        for f in FINGERS:
            js = [idx["EXP_%s_%s%d" % (side, f, k)] for k in (1, 2, 3)]
            parent = par[js[0]]
            base_tip = chain_tip(side, f, {})
            jl = []
            for k, j in enumerate(js):
                # bone direction in world: to the next joint, or along the last bone
                b = unit((WP[js[k + 1]] - WP[j]) if k < 2 else (WP[j] - WP[js[1]]))
                bl = unit(qrot(conj(WQ[j]), b))
                # candidate hinge: the joint-local cardinal axis most perpendicular to
                # the bone that moves the tip the most toward the palm pad
                # ⛔ NOT "whichever axis moves the tip closest to the palm pad": the
                # pad sits off-centre, so for the edge fingers (index, pinky) a
                # SIDEWAYS swing wins that test -- which is exactly the bent-sideways
                # pinky seen in game. A finger's hinge runs parallel to the knuckle
                # line, so pick the local cardinal axis most aligned with it, and use
                # the palm-pad test only for its SIGN.
                c = int(np.argmax([abs(np.dot(qrot(WQ[j], np.eye(3)[i]), P)) for i in range(3)]))
                best = None
                for sgn in (1.0, -1.0):
                    ax = np.zeros(3); ax[c] = sgn
                    tip = chain_tip(side, f, {k: aa(ax, 30)})
                    gain = np.linalg.norm(base_tip - pad) - np.linalg.norm(tip - pad)
                    if best is None or gain > best[0]: best = (gain, ax)
                gain, ax = best
                if f == "Thumb":
                    # the thumb folds across the palm on a tilted axis; keep the
                    # geometric one (toward the pinky knuckle) when it does better
                    m = kP - WP[j]; m = unit(m - np.dot(m, b) * b)
                    aw = unit(np.cross(b, m)); al = unit(qrot(conj(WQ[j]), aw))
                    tip = chain_tip(side, f, {k: aa(al, 30)})
                    g2 = np.linalg.norm(base_tip - pad) - np.linalg.norm(tip - pad)
                    if g2 > gain: gain, ax = g2, al
                assert gain > 0, "%s %s joint %d: no axis curls toward the palm" % (side, f, k + 1)
                # twist sign: spinning the hinge about the bone by +t adds a pinky-side
                # component to the motion when sign(dot(b x u, P)) > 0, u = a x b
                aw = qrot(WQ[j], ax); u = np.cross(aw, b)
                ts = 1.0 if np.dot(np.cross(b, u), P) >= 0 else -1.0
                jl.append((j, localq[j], ax, bl, ts))
                report.append("%s %-6s j%d #%3d  axis(%+.2f %+.2f %+.2f)  tip %.1f mm closer per 30deg"
                              % (side, f, k + 1, j, *ax, gain * 1000))
            # knuckle spread axis: swings the first bone toward the pinky side
            b0 = unit(WP[js[1]] - WP[js[0]])
            ps = unit(P - np.dot(P, b0) * b0)
            sp = unit(qrot(conj(WQ[js[0]]), unit(np.cross(b0, ps))))
            fmt3 = lambda v: "{%.6ff, %.6ff, %.6ff}" % tuple(v)
            fmt4 = lambda v: "{%.6ff, %.6ff, %.6ff, %.6ff}" % tuple(v)
            joints = ", ".join("{%d, %s, %s, %s, %.1ff}" % (j, fmt4(q), fmt3(a), fmt3(bl), ts)
                               for j, q, a, bl, ts in jl)
            lines.append("    { %d, { %s }, %s },   // %s" % (parent, joints, fmt3(sp), f))
        lines.append("  } },")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(report))
    print("\nwrote", OUT)


if __name__ == "__main__":
    main()
